apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod-otlp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod-otlp
  template:
    metadata:
      labels:
        app: hotrod-otlp
    spec:
      containers:
      - name: hotrod
        image: jaegertracing/example-hotrod:latest
        ports:
        - containerPort: 8080
        env:
        # OTLP 설정 (최신 방식)
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://jaeger-collector.observability.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_SERVICE_NAME
          value: "hotrod-jaeger"
        # 샘플링 설정
        - name: OTEL_TRACES_SAMPLER
          value: "always_on"
---
apiVersion: v1
kind: Service
metadata:
  name: hotrod-otlp
spec:
  selector:
    app: hotrod-otlp
  ports:
  - port: 8082
    targetPort: 8080
  type: NodePort