apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
      - name: hotrod
        image: jaegertracing/example-hotrod:latest
        ports:
        - containerPort: 8080
        env:
        # OTLP 설정 (주요!)
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        # Jaeger 설정 (백업)
        - name: JAEGER_ENDPOINT
          value: "http://tempo:14268/api/traces"
        - name: JAEGER_AGENT_HOST
          value: "tempo"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        # 샘플링 설정
        - name: JAEGER_SAMPLER_TYPE
          value: "const"
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: hotrod
spec:
  selector:
    app: hotrod
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort